# Standard libraries
from decimal import Decimal
from typing import Final

CENT_QUANTIZE: Final[Decimal] = Decimal("0.01")

# Manual overrides for ISINs not resolved correctly by yfinance
ISIN_MAPPING: Final[dict[str, str]] = {"IE000I8KRLL9": "SEMI.AS"}

ETF_LIST_NAME: Final[tuple[str, ...]] = (
    "ishares",
    "vanguard",
    "xtrackers",
    "spdr",
    "amundi",
    "lyxor",
    "invesco",
    "hsbc",
    "fidelity",
    "wisdomtree",
    "vaneck",
    "schwab",
    "global x",
    "state street",
    "dimensional",
    "first trust",
    "j.p. morgan",
    "goldman sachs",
    "ubs",
    "franklin templeton",
)

SECTOR_MAP: Final[dict[str, str]] = {
    # Spanish -> English (iShares ES)
    "Tecnología de la Información": "Technology",
    "Financieros": "Financials",
    "Industriales": "Industrials",
    "Materiales": "Materials",
    "Consumo discrecional": "Consumer Discretionary",
    "Cuidado de la Salud": "Health Care",
    "Comunicación": "Communication",
    "Productos básicos de consumo": "Consumer Staples",
    "Energía": "Energy",
    "Servicios": "Utilities",
    "Inmobiliario": "Real Estate",
    "Otro": "Other",
    # Vanguard / alternative English names
    "Consumer Defensive": "Consumer Staples",
    "Basic Materials": "Materials",
    "Telecommunications": "Communication",
}

COUNTRY_MAP: Final[dict[str, str]] = {
    # Spanish -> English (iShares ES)
    "Estados Unidos": "United States",
    "Reino Unido": "United Kingdom",
    "Alemania": "Germany",
    "Francia": "France",
    "Suiza": "Switzerland",
    "Holanda": "Netherlands",
    "Suecia": "Sweden",
    "España": "Spain",
    "Italia": "Italy",
    "Dinamarca": "Denmark",
    "Finlandia": "Finland",
    "Noruega": "Norway",
    "Bélgica": "Belgium",
    "Irlanda": "Ireland",
    "Austria": "Austria",
    "Canadá": "Canada",
    "Japón": "Japan",
    "Taiwán": "Taiwan",
    "Corea": "South Korea",
    "Filipinas": "Philippines",
    "Tailandia": "Thailand",
    "Malasia": "Malaysia",
    "Singapur": "Singapore",
    "Nueva Zelanda": "New Zealand",
    "Brasil": "Brazil",
    "México": "Mexico",
    "Sudáfrica": "South Africa",
    "Egipto": "Egypt",
    "Arabia Saudita": "Saudi Arabia",
    "Emiratos Árabes Unidos": "United Arab Emirates",
    "Polonia": "Poland",
    "Grecia": "Greece",
    "Hungría": "Hungary",
    "República Checa": "Czech Republic",
    "Perú": "Peru",
    "Turquía": "Turkey",
    "Rusia": "Russia",
    # ISO 2-letter codes (Vanguard)
    "AT": "Austria",
    "BE": "Belgium",
    "CH": "Switzerland",
    "DE": "Germany",
    "DK": "Denmark",
    "ES": "Spain",
    "FI": "Finland",
    "FR": "France",
    "GB": "United Kingdom",
    "IE": "Ireland",
    "IT": "Italy",
    "NL": "Netherlands",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "SE": "Sweden",
}

CONTINENT_MAP: Final[dict[str, str]] = {
    "United States": "North America",
    "Canada": "North America",
    "Mexico": "North America",
    "United Kingdom": "Europe",
    "Germany": "Europe",
    "France": "Europe",
    "Switzerland": "Europe",
    "Netherlands": "Europe",
    "Sweden": "Europe",
    "Spain": "Europe",
    "Italy": "Europe",
    "Denmark": "Europe",
    "Finland": "Europe",
    "Norway": "Europe",
    "Belgium": "Europe",
    "Ireland": "Europe",
    "Austria": "Europe",
    "Portugal": "Europe",
    "Poland": "Europe",
    "Greece": "Europe",
    "Czech Republic": "Europe",
    "Hungary": "Europe",
    "Russia": "Europe",
    "Japan": "Asia",
    "China": "Asia",
    "Taiwan": "Asia",
    "South Korea": "Asia",
    "India": "Asia",
    "Hong Kong": "Asia",
    "Singapore": "Asia",
    "Thailand": "Asia",
    "Indonesia": "Asia",
    "Malaysia": "Asia",
    "Philippines": "Asia",
    "Vietnam": "Asia",
    "Pakistan": "Asia",
    "Bangladesh": "Asia",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    "Brazil": "South America",
    "Chile": "South America",
    "Colombia": "South America",
    "Peru": "South America",
    "Argentina": "South America",
    "South Africa": "Africa",
    "Nigeria": "Africa",
    "Egypt": "Africa",
    "Kenya": "Africa",
    "Morocco": "Africa",
    "Saudi Arabia": "Middle East",
    "United Arab Emirates": "Middle East",
    "Israel": "Middle East",
    "Qatar": "Middle East",
    "Kuwait": "Middle East",
    "Turkey": "Middle East",
}
